Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "scripting01",
      :box => "generic/rhel9",
      :ip => "192.168.56.100",
      :ssh_port => '2210'
    },
    {
      :hostname => "scripting02",
      :box => "generic/rhel9",
      :ip => "192.168.56.11",
      :ssh_port => '2211'
    },
  ]

  servers.each do |machine|

    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
    
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--name", machine[:hostname]]
      end
    end
  end

end